- id: js-beautify
  name: js-beautify
  entry: js-beautify
  language: node
  additional_dependencies: [ 'js-beautify@1.14.8' ]
  minimum_pre_commit_version: 2.0.0
  description: "Runs `js-beautify`"
